# This is a basic workflow to help you get started with Actions

name: avenue Town

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: cashier, criminal, police, fighter, sport player, waiter, teacher, nurse, youTuber, actor, news, reporter, lifeguard, bodyguard, military farmer, construction worker, made, pilot, security, taxi driver, janitor, mirror, chef, dancer, sheriff, principal, student, astronaut
  # This workflow contains a single job called "build"
  build: houses, stores, police station, fire station, robbers base
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
